train:
  _target_: src.datasets.CustomDirDataset
  dataset_dir: 'LJSpeech-1.1'
  part: 'train'
  max_text_length: 128
  limit: 12

val:
  _target_: src.datasets.CustomDirDataset
  dataset_dir: 'LJSpeech-1.1'
  part: 'val'
  max_text_length: 128
  limit: 12
